AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  pAppName:
    Type: String
    Description: Application Name deployed in this stack
    Default: call-intent

  pEnvironmentName:
    Type: String
    Default: dev
    Description: The name of the specific stack deployment e.g. 'dev'

  pCorsOrigin:
    Type: String
    Description: The CORS origin for the API

  pPrismaLayerVersion:
    Type: String
    Description: The version of the Prisma Layer to use

  pDatabaseUrl:
    Type: String
    Description: The Database URL for the API to connect to.

Globals:
 Function:
    Runtime: nodejs22.x
    Environment:
      Variables:
        DATABASE_URL: !Ref pDatabaseUrl
    MemorySize: 256
    Timeout: 30

Resources:
  CategoriesApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowMethods: ['GET', 'OPTIONS']
        AllowHeaders: ['*']
        AllowOrigins: ['*']
        MaxAge: 300
      ProtocolVersion: HTTP2
      SecurityPolicy: TLS_1_2

  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/lambda/categories/get
      Runtime: nodejs22.x
      Events:
        GetCategories:
          Type: HttpApi
          Properties:
            ApiId: !Ref CategoriesApi
            Path: /categories
            Method: GET

  GetCategoryByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/lambda/categories/get-by-id
      Runtime: nodejs22.x
      Events:
        GetCategoryById:
          Type: HttpApi
          Properties:
            ApiId: !Ref CategoriesApi
            Path: /categories/{id}
            Method: GET

Outputs:
  ApiUrl:
    Description: URL of your API
    Value: !Sub 'https://${CategoriesApi}.execute-api.${AWS::Region}.amazonaws.com'